// Centralised audit event names – no hardcoded strings elsewhere.

const SETTINGS_EVENTS = {
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  ACCOUNT_DELETED_REQUESTED: 'ACCOUNT_DELETED_REQUESTED',
  PAYMENT_METHOD_ADDED: 'PAYMENT_METHOD_ADDED',
  PAYMENT_METHOD_REMOVED: 'PAYMENT_METHOD_REMOVED',
  PAYMENT_METHOD_UPDATED: 'PAYMENT_METHOD_UPDATED',
  NOTIFICATION_PREFERENCE_CHANGED: 'NOTIFICATION_PREFERENCE_CHANGED',
};

module.exports = { SETTINGS_EVENTS };