ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS extra_items_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS final_total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS invoice_confirmed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS paid_by_role VARCHAR(20),
  ADD COLUMN IF NOT EXISTS paid_by_user INTEGER;