ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS profession_id INTEGER REFERENCES professions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS service_id INTEGER REFERENCES profession_services(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS service_label VARCHAR(150),
  ADD COLUMN IF NOT EXISTS service_price DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS profession_label VARCHAR(100);